---
- name: Install eclipse
  unarchive:
    remote_src: yes
    src: 'https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/oxygen/3a/eclipse-committers-oxygen-3a-linux-gtk-x86_64.tar.gz&r=1'
    # This will create ~/eclipse/eclipse, containing an eclipse executable.
    dest: '{{ ansible_user_dir }}/eclipse/'
    creates: '{{ ansible_user_dir }}/eclipse/eclipse/eclipse'
  tags:
    - eclipse

- name: Add eclipse.desktop file
  template:
    src: eclipse-local.desktop.j2
    dest: "{{ ansible_user_dir }}/.local/share/applications/eclipse-local.desktop"
  tags:
    - eclipse
