---
- name: Install eclipse
  package: name={{ item }}
  with_items:
    - eclipse-anyedit
    - eclipse-cdt
    - eclipse-color-theme
    - eclipse-dltk
    - eclipse-dltk-mylyn
    - eclipse-dltk-sh
    - eclipse-egit
    - eclipse-egit-github
    - eclipse-egit-mylyn
    - eclipse-jdt
    - eclipse-linuxtools
    - eclipse-moreunit
    - eclipse-mpc
    - eclipse-mylyn
    - eclipse-mylyn-builds-hudson
    - eclipse-mylyn-docs-wikitext
    - eclipse-mylyn-tasks-bugzilla
    - eclipse-mylyn-versions-git
    - eclipse-mylyn-versions-subclipse
    - eclipse-packagekit
    - eclipse-pde
    - eclipse-platform
    - eclipse-pydev
    - eclipse-pydev-mylyn
    - eclipse-recommenders
    - eclipse-subclipse
    - eclipse-tm-terminal
    - eclipse-tm-terminal-connectors
    - eclipse-webtools-sourceediting
    # Still missing: YEdit
    # Also missing: Mylyn GitLab connector
    # Maybe also missing: XML editors and tools / WST?  Gitflow support?  JavaScript development tools?
  tags:
    - eclipse
