---
- name: Install eclipse
  unarchive:
    src: 'https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/oxygen/3a/eclipse-committers-oxygen-3a-linux-gtk-x86_64.tar.gz&r=1'
    # This will create ~/eclipse/eclipse, containing an eclipse executable.
    dest: '{{ ansible_user_dir }}/eclipse/'
    creates: '{{ ansible_user_dir }}/eclipse/eclipse/eclipse'
    # Still missing: YEdit
    # Also missing: Mylyn GitLab connector
    # Maybe also missing: XML editors and tools / WST?  Gitflow support?  JavaScript development tools?
  tags:
    - eclipse
