---
# do the following as root
- hosts: localhost
  become: true
  roles:
    - basic_packages
    - inotify_max_user_watches
#    - atom

# run the following as the calling user
- hosts: localhost
  connection: local
  become: false
  roles:
    - user_tasks
    - flathub
