---
# Tasks to be performed as calling user
- name: link some autostart programs
  file:
    src: "/usr/share/applications/{{ item }}"
    dest: "~/.config/autostart/{{ item }}"
    state: link
  with_items:
    - "io.github.Hexchat.desktop"
    - "mozilla-thunderbird-wayland.desktop"
    - "nautilus-autorun-software.desktop"
    - "org.gnome.Terminal.desktop"
    - "org.keepassxc.KeePassXC.desktop"
    - "codium.desktop"

- name: link flatpak autostart programs
  file:
    src: "/var/lib/flatpak/exports/share/applications/{{ item }}"
    dest: "~/.config/autostart/{{ item }}"
    state: link
  with_items:
    - "org.signal.Signal.desktop"
