---
- name: Add flathub repo
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: 'https://flathub.org/repo/flathub.flatpakrepo'

- name: Install VSCodium
  flatpak:
    name: VSCodium
    state: present

