---
- name: Install basic packages
  package:
    state: present
    name:
      - "@Fedora Workstation"
      - "@C Development Tools and Libraries"
#      - "@GNOME Desktop Environment"
      - ImageMagick
      - alsa-utils
      - android-tools
      - ansible
      - ant
      - aspell
      - aspell-de
      - aspell-en
      - atop
      - autofs
      - automake
      - autossh
      - baobab
      - bind-utils
      - binutils
      - brasero
      - bridge-utils
      - byobu
      - cabextract
      - calibre
      - cifs-utils
      - coreutils
      - dbus-tools
      - dconf-editor
      - desktop-backgrounds-basic
      - desktop-backgrounds-gnome
      - desktop-file-utils
      - diffutils
      - dmidecode
      - dnf-utils
      - docker
      - docker-compose
      - dos2unix
      - dosfstools
      - e2fsprogs
      - ecryptfs-utils
      - elfutils
      - eog
      - espeak
      - espeak-ng
      - etherape
      - evolution
      - evolution-ews
      - exiv2
      - fdupes
      - festival
      - file
      - findutils
      - firefox
      - flatpak
      - gconf-editor
      - gimp
      - gimp-help-de
      - git
      - git-extras
      - glabels
      - glabels-templates
      - gparted
      - gradio
      - hdparm
      - hexchat
      - heimdall
      - highlight
      - hunspell-de
      - hyphen-de
      - imapfilter
      - indent
      - iputils
      - keepassxc
      - langpacks-core-de
      - langpacks-de
      - lensfun
      - less
      - libreoffice
      - lm_sensors
      - lshw
      - lsof
      - make
      - mkpasswd
#      - mplayer
      - mtools
      - mythes-de
      - net-tools
      - nethogs
      - netpbm
      - nextcloud-client
      - nextcloud-client-nautilus
      - nfs-utils
      - nmap
      - ntfsprogs
      - openssh
      - openvpn
      - os-prober
      - p0f
      - patch
      - patchutils
      - perl-Image-ExifTool
      - php-cli
      - pidgin
      - pidgin-indicator
      - poedit
      - poppler-utils
      - powerline
      - powerline-fonts
      - psmisc
      - pulseaudio-utils
      - python3-libselinux
      - python3-ansible-lint
      - rdesktop
      - recode
      - remmina
      - remmina-plugins-exec
      - remmina-plugins-rdp
      - remmina-plugins-secret
      - remmina-plugins-st
      - remmina-plugins-vnc
      - rhythmbox
      - rsync
      - screen
      - seahorse
      - setroubleshoot
      - setroubleshoot-plugins
      - sloccount
      - smartmontools
      - sox
      - sqlite
      - strace
      - subversion
      - swaks
      - symlinks
      - tar
      - tcpdump
      - telnet
      - testdisk
      - texlive
      - thunderbird
      - thunderbird-enigmail
      - thunderbird-wayland
      - tmux
      - tmux-powerline
      - traceroute
      - tree
      - ufraw
      - usbutils
      - vim-X11
      - vim-enhanced
      - vim-powerline
      - vinagre
      - vino
      - virt-manager
 #     - vlc
 #     - vlc-extras
      - wget
      - which
      - wireshark
      - wmctrl
      - xdg-utils
      - xdotool
      - xmlrpc-client
      - yamllint
      - zip

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpaks from flathub
  flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  with_items:
    - org.signal.Signal
    - de.haeckerfelix.Shortwave

- name: vscodium - import required gpgkey
  rpm_key:
    state: present
    key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg

- name: vscodium - add required repository
  yum_repository:
    name: gitlab.com_paulcarroty_vscodium_repo
    description: Binary release repo for VSCodium
    baseurl: https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/
    gpgkey: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    gpgcheck: yes
    repo_gpgcheck: yes

- name: vscodium - install binary
  package:
    state: present
    name:
      - codium

- name: enable sshd.service
  systemd:
    name: sshd
    enabled: yes
    state: started


#- name: Atom install
#  package:
#    state: present
#    name:
#      - redhat-lsb-core
#      - clang
