---
- name: Install basic packages
  package:
    state: present
    name:
#      - "@Fedora Workstation"
#      - "@C Development Tools and Libraries"
#      - "@GNOME Desktop Environment"
      - binutils
      - imagemagick
      - alacarte
      - alsa-utils
#      - android-tools
      - ansible
      - ant
      - aspell
      - aspell-de
      - aspell-en
      - atop
      - automake
      - avrdude
      - binutils-avr
      - baobab
      - bind9-utils
      - binutils
      - brasero
      - bridge-utils
      - byobu
      - cabextract
      - calibre
      - cifs-utils
      - coreutils
#      - dbus-tools
      - dconf-editor
#      - desktop-backgrounds-basic
#      - desktop-backgrounds-gnome
#      - desktop-file-utils
      - diffutils
      - dmidecode
#      - dnf-utils
      - docker
      - docker-compose
      - dos2unix
      - dosfstools
      - e2fsprogs
      - elfutils
      - eog
      - espeak
      - espeak-ng
      - etherape
      - evolution-data-server
#      - evolution-ews
      - exiv2
      - fdupes
      - festival
      - file
      - findutils
      - firefox
      - flatpak
      - freecad
      - gconf-editor
      - gimp
      - gimp-help-de
      - git
      - git-extras
      - glabels
      - glabels-data
      - gparted
#      - gradio
#      - gstreamer-tools
      - hdparm
      - heimdall
      - highlight
      - hunspell-de
      - hyphen-de
      - imapfilter
      - indent
      - iputils
      - keepassxc
#      - langpacks-core-de
#      - langpacks-de
      - gimp-lensfun
      - less
      - libreoffice
      - lm_sensors
      - lshw
      - lsof
      - make
      - mkpasswd
      - mplayer
      - mtools
      - mythes-de
      - nano
      - net-tools
      - nethogs
      - netpbm
      - nextcloud-client
      - nfs-utils
      - nmap
      - ntfsprogs
      - openssh
      - openvpn
      - os-prober
      - p0f
      - patch
      - patchutils
      - perl-Image-ExifTool
      - php-cli
      - pidgin
      - pidgin-indicator
      - poedit
      - poppler-utils
      - powerline
      - powerline-fonts
      - psmisc
      - pulseaudio-utils
      - python3-libselinux
      - python3-ansible-lint
      - rdesktop
      - recode
      - remmina
      - remmina-plugin-exec
      - remmina-plugin-rdp
      - remmina-plugin-secret
#      - remmina-plugin-st
      - remmina-plugin-vnc
      - rhythmbox
      - rsync
      - screen
      - seahorse
#      - setroubleshoot
#      - setroubleshoot-plugins
      - sloccount
      - smartmontools
      - sox
      - sqlite
      - strace
      - subversion
      - swaks
      - symlinks
      - tar
      - tcpdump
      - telnet
      - testdisk
      - texlive
      - thunderbird
      - enigmail
      - thunderbird-gnome-support
      - thunderbird-locale-de
      - tmux
      - tmuxinator
      - traceroute
      - tree
      - ufraw
      - usbutils
      - vim-gtk3
      - vim-scripts
#      - vim-powerline
      - vinagre
      - vino
      - vlc
      - vlc-extras
      - wget
      - which
      - wireshark
      - wmctrl
      - xdg-utils
      - xdotool
      - xirc
      - xmlrpc-api-utils
      - yamllint
      - zip
