---
- name: Install basic packages
  package:
    state: present
    name:
#      - "@Fedora Workstation"
#      - "@C Development Tools and Libraries"
#      - "@GNOME Desktop Environment"
      - binutils
      - imagemagick
      - alacarte
      - alsa-utils
#      - android-tools
      - ansible
      - ant
      - aspell
      - aspell-de
      - aspell-en
      - atop
      - automake
      - avrdude
      - binutils-avr
      - baobab
      - bind9-utils
      - binutils
      - brasero
      - bridge-utils
      - byobu
      - cabextract
      - calibre
      - cifs-utils
      - coreutils
#      - dbus-tools
      - dconf-editor
      - default-jdk-headless

      - default-jdk-headless

#      - desktop-backgrounds-basic
#      - desktop-backgrounds-gnome
#      - desktop-file-utils
      - diffutils
      - dmidecode
#      - dnf-utils
      - docker
      - docker-compose
      - dos2unix
      - dosfstools
      - e2fsprogs
      - elfutils
      - eog
      - espeak
      - espeak-ng
      - etherape
      - evolution-data-server
#      - evolution-ews
      - exiv2
      - fdupes
      - festival
      - file
      - findutils
      - firefox
      - flatpak
      - freecad
      - gconf-editor
      - gimp
      - gimp-help-de
      - git
      - git-extras
      - glabels
      - glabels-data
      - gparted
#      - gradio
#      - gstreamer-tools
      - hdparm
#      - heimdall
      - highlight
      - hunspell-de-de
      - hyphen-de
      - imapfilter
      - indent
#      - iputils
      - keepassxc
#      - langpacks-core-de
#      - langpacks-de
      - gimp-lensfun
      - less
      - libreoffice
      - lm-sensors
      - lshw
      - lsof
      - make
      - passwd
      - mplayer
      - mtools
      - mythes-de
      - nano
      - net-tools
      - nethogs
      - netpbm
      - netplan.io
      - nextcloud-desktop
      - nextcloud-desktop-cmd
      - network-manager-openvpn
      - network-manager-openvpn-gnome
      - network-manager-config-connectivity-ubuntu
      - networkd-dispatcher
      - nfs-common
      - ninja-build
      - nmap
      - nmap-common
      - libntfs-utils
      - nmapsi4
      - nodejs
#Setup node-js - todo
#      - 
      - notify-osd
      - notify-osd-icons
      - ntopng
      - ntopng-data
      - nux-tools
      - ocrfeeder
      - okular
      - okular-extra-backends
      - openipmi
      - openjdk-11-jdk:amd64
      - openjdk-11-jdk-headless:amd64
      - openjdk-11-jre:amd64
      - openjdk-11-jre-headless:amd64
      - openjdk-14-jre:amd64
      - openjdk-14-jre-headless:amd64
      - openjfx
      - openjfx-source
      - openmpi-bin
      - openpgp-applet
      - openshot
      - openshot-qt
      - openssh-client
      - openssh-server
      - openssl
      - openvpn
      - openvpn-systemd-resolved
      - orca
      - os-prober
      - osinfo-db
      - ovmf
      - p0f
      - patch
      - parted
      - p11-kit
      - packagekit
      - packagekit-tools
      - pci.ids
      - patchutils
      - libimage-exiftool-perl
      - php-cli
      - pidgin
      - pidgin-data
      - pidgin-plugin-pack
#      - poedit
#      - poppler-utils
#      - powerline
#      - powerline-fonts
      - psmisc
      - pulseaudio-utils
      - python3-libselinux
      - python3-ansible-lint
      - rdesktop
      - recode
      - remmina
      - remmina-plugin-exec
      - remmina-plugin-rdp
      - remmina-plugin-secret
#      - remmina-plugin-st
      - remmina-plugin-vnc
      - rhythmbox
      - rsync
      - screen
      - seahorse
#      - setroubleshoot
#      - setroubleshoot-plugins
      - sloccount
      - smartmontools
      - sox
      - sqlite3
      - strace
      - subversion-tools
      - swaks
      - symlinks
      - tar
      - tcpdump
      - telnet
      - testdisk
      - texlive
      - thunderbird
      - enigmail
      - thunderbird-gnome-support
      - thunderbird-locale-de
      - tmux
      - tmuxinator
      - traceroute
      - tree
#      - ufraw
      - usbutils
      - vim-gtk3
      - vim-scripts
#      - vim-powerline
      - vinagre
      - vino
      - vlc
      - vlc-extras
      - wget
      - which
      - wireshark
      - wmctrl
      - xdg-utils
      - xdotool
      - hexchat
      - xmlrpc-api-utils
      - yamllint
      - zip
