---
- name: tweak dnf a little bit
  lineinfile:
    path: "/etc/dnf/dnf.conf"
    line: "{{ item }}"
  with_items:
    - "fastestmirror=1"
    - "max_parallel_downloads=10"
    - "deltarpm=true"

- name: Install basic packages
  package:
    state: present
    name:
      - "@Fedora Workstation"
      - "@C Development Tools and Libraries"
#      - "@GNOME Desktop Environment"
      - "@3d-printing"
      - ImageMagick
      - alsa-utils
      - android-tools
      - ansible
      - ant
      - aspell
      - aspell-de
      - aspell-en
      - atop
      - autofs
      - automake
      - autossh
      - baobab
      - bind-utils
      - binutils
      - brasero
      - bridge-utils
      - byobu
      - cabextract
      - calibre
      - cifs-utils
      - coreutils
#      - chromium-browser-privacy
# Part of rpmfusion
      - dbus-tools
      - dconf-editor
      - desktop-backgrounds-basic
      - desktop-backgrounds-gnome
      - desktop-file-utils
      - distribution-gpg-keys
      - diffutils
      - dmidecode
      - dnf-utils
      - docker
      - docker-compose
      - dos2unix
      - dosfstools
      - e2fsprogs
      - ecryptfs-utils
      - elfutils
      - eog
      - espeak
      - espeak-ng
      - etherape
      - evolution
      - evolution-ews
      - exiv2
      - fdupes
      - festival
      - file
      - findutils
      - firefox
      - flatpak
      - gconf-editor
      - gimp
      - gimp-help-de
      - git
      - git-extras
      - glabels
      - glabels-templates
      - gnome-tweaks
      - gnome-extension-app
      - gparted
      - gradio
      - hdparm
      - hexchat
      - heimdall
      - highlight
      - hunspell-de
      - hyphen-de
      - imapfilter
      - indent
      - iputils
      - keepassxc
      - kernel-devel
      - langpacks-core-de
      - langpacks-de
      - lensfun
      - less
      - libreoffice
      - lm_sensors
      - lshw
      - lsof
      - make
      - mkpasswd
      - mosquitto
#      - mplayer
      - mtools
      - mythes-de
      - net-tools
      - nethogs
      - netpbm
      - nextcloud-client
      - nextcloud-client-nautilus
      - nfs-utils
      - nmap
      - ntfsprogs
      - openssh
      - openvpn
      - os-prober
      - p0f
      - patch
      - patchutils
      - perl-Image-ExifTool
      - php-cli
      - pidgin
      - pidgin-indicator
      - poedit
      - poppler-utils
      - powerline
      - powerline-fonts
      - powertop
      - psmisc
      - pulseaudio-utils
      - python3-libselinux
      - python3-ansible-lint
      - python3-dnf-plugin-versionlock
      - rdesktop
      - recode
      - remmina
      - remmina-plugins-exec
      - remmina-plugins-rdp
      - remmina-plugins-secret
      - remmina-plugins-st
      - remmina-plugins-vnc
      - rhythmbox
      - rsync
      - screen
      - seahorse
      - setroubleshoot
      - setroubleshoot-plugins
      - sloccount
      - smartmontools
      - sox
      - sqlite
      - strace
      - subversion
      - swaks
      - symlinks
      - tar
      - tcpdump
      - telnet
      - testdisk
      - texlive
#      - thunderbird
#      - thunderbird-enigmail
# wayland got default, enigmail no longer avail
      - thunderbird-wayland
      - tmux
      - tmux-powerline
      - traceroute
      - tree
      - ufraw
#      - ungoogled-chromium
      - usbutils
      - vim-X11
      - vim-enhanced
      - vim-powerline
      - vinagre
#      - vino
# not yet in 34
      - virt-manager
#      - vlc
#      - vlc-extras
      - wget
      - which
      - wireshark
      - wmctrl
      - xdg-utils
      - xdotool
      - xmlrpc-client
      - yamllint
      - zip

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpaks from flathub
  flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  with_items:
    - org.signal.Signal
#    - de.haeckerfelix.Shortwave
# Up to now not used by myself and just cluttering selinux problems.

- name: vscodium - import required gpgkey
  rpm_key:
    state: present
    key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg

- name: vscodium - add required repository
  yum_repository:
    name: gitlab.com_paulcarroty_vscodium_repo
    description: Binary release repo for VSCodium
    baseurl: https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/
    gpgkey: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    gpgcheck: yes
    repo_gpgcheck: yes

- name: vscodium - install binary
  package:
    state: present
    name:
      - codium

- name: enable sshd.service
  systemd:
    name: sshd
    enabled: yes
    state: started

- name: install rpm fusion - free
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Fedora'

- name: install rpm fusion - nonfree
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Fedora'

- name: update dnf
  dnf:
    name: 
      - dnf-plugins-core
      - vlc
      - libdvdcss
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-free-extra
      - gstreamer1-plugins-freeworld
      - gstreamer1-plugins-good
      - gstreamer1-plugins-good-extra
      - gstreamer1-plugins-good-gtk
      - gstreamer1-plugins-ugly
      - gstreamer1-plugins-ugly-free
      - gstreamer1-plugin-openh264 
      - mozilla-openh264
state: present
