---
- name: Install python-firewall
  package: name=python-firewall

- name: Open tcp port 2049 for nfs
  firewalld:
    service: nfs
    permanent: true
    state: enabled

- name: Open udp port 111
  firewalld:
    service: rpc-bind
    permanent: true
    state: enabled

- name: Install NFS packages
  package: name={{ item }}
  with_items:
    - libnfs-utils
    - nfs-utils
